version: "3.9"
services:
    api:
        build: ./app
        command: cargo run
        working_dir: /app
        volumes:
            - ./data:/app/data
        ports: 
            - 8080:8080
        tty: true
        env_file: 
            - ./.env

    tor:
        build: ./tor
        ports:
            - "9050:9050"
        volumes:
            - ./data/tor:/var/lib/tor
            - ./tor/torrc:/etc/tor/torrc
        depends_on: 
            - api
