services:
    app:
        image: rust:latest
        command: cargo run
        working_dir: /app
        volumes:
            - ./:/app
        ports: 
            - 8080:8080
        environment:
            - USER=aias
        tty: true
    
