version: "3.9"
services:
    api:
        build: ./app
        command: cargo run
        working_dir: /app
        volumes:
            - ./app:/app/
            - ./data/app/registry:/usr/local/cargo/registry/
        tty: true
        env_file: 
            - ./.env

    tor:
        build: ./tor
        volumes:
            - ./data/tor:/var/lib/tor
            - ./tor/torrc:/etc/tor/torrc
        depends_on: 
            - api
