version: "3.9"
services:
    app:
        build: ./app
        command: cargo run
        working_dir: /app
        volumes:
            - ./data:/app/data
        ports: 
            - 8080:8080
        tty: true